### ISSUE TITLE
[question] What's the usage of `start` file?

### ISSUE THREAD

**Issue by liaodalin19903** [Ibrahimrahhal/ast-playground#2]
Hi, what's the usage of:  [start](https://github.com/Ibrahimrahhal/ast-playground/blob/main/start) file

I dodn't see any code about it, what is it designed for?

**Comment by Ibrahimrahhal** [comment]
Hi @liaodalin19903, Its just an empty file I committed to mark my starting time of working on the project. It doesn't do anything.
